services:
  - type: web
    name: antenna-cloud-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    runtime: python-3.11.8
